"""initial foundation schema

Revision ID: 93091655a083
Revises: 
Create Date: 2026-06-03 00:50:23.785971
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '93091655a083'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('bar_license_number', sa.String(), nullable=True),
    sa.Column('digital_signature_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('parcel', sa.String(), nullable=False),
    sa.Column('sub_parcel', sa.String(), nullable=True),
    sa.Column('property_address', sa.String(), nullable=False),
    sa.Column('property_city', sa.String(), nullable=False),
    sa.Column('deal_type', sa.String(), nullable=False),
    sa.Column('deal_value_ils', sa.Integer(), nullable=True),
    sa.Column('primary_lawyer_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_lawyer_name', sa.String(), nullable=True),
    sa.Column('counterparty_lawyer_phone', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signing_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intake_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tax_calculation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('municipal_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identity_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('taboo_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condo_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contract_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('addenda_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags_count', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('related_step', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('israeli_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('identity_check_status', sa.String(), nullable=False),
    sa.Column('identity_check_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parties')
    op.drop_table('documents')
    op.drop_table('activities')
    op.drop_table('cases')
    op.drop_table('users')
    # ### end Alembic commands ###
